const actionTypes = {
  LOAD_PHOTOS: 'LOAD_PHOTOS',
  SHOW_BIG_PHOTO: 'SHOW_BIG_PHOTO',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  TOGGLE_LIKE_PHOTO: 'TOGGLE_LIKE_PHOTO',
  TOGGLE_AUTHORIZATION: 'TOGGLE_AUTHORIZATION',
  FROM_URL: 'FROM_URL',
};

export default actionTypes;
